from src.utils import GetMistralAI
from src.state import ChatState
from langchain_core.messages import SystemMessage
import logging
from src.exceptions import CustomException
import sys

logger = logging.getLogger(__name__)

llm = GetMistralAI()

MAX_HISTORY = 10

SYSTEM_PROMPT = SystemMessage(content=(
    "You are a helpful assistant. Always give complete answers. "
    "Be concise and never cut off mid-sentence. "
    "Keep replies under 400 words."
    "Try To do not lose any important imformation and facts"
))

def Chat_nodes(state: ChatState) -> dict:

    try:
        """ Takes messages from state, sends to LLM, returns response. """
        messages = state["messages"]
        

        # Only send the last MAX_HISTORY messages to the LLM
        trimmed = messages[-MAX_HISTORY:]

        # Prepend system prompt so llm knows to be concise and complete
        final_messages = [SYSTEM_PROMPT] + list(trimmed)

        # Call the LLM and get back a proper AIMessage object
        response = llm.invoke(final_messages)
        logger.info("Response generated by LLM...")

        # Return the AIMessage — LangGraph's add_messages reducer stores it in state
        return {"messages": [response]}
    except Exception as e:
        logger.error("Chat_nodes failed", exc_info=True)
        raise CustomException(e, sys)
